# Generated by Django 6.0.2 on 2026-02-26 18:57

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Angebot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=50, unique=True, verbose_name='Angebotsnummer')),
                ('datum', models.DateField(default=django.utils.timezone.now, verbose_name='Datum')),
                ('gueltig_bis', models.DateField(blank=True, null=True, verbose_name='Gültig bis')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('gesendet', 'Gesendet'), ('angenommen', 'Angenommen'), ('abgelehnt', 'Abgelehnt'), ('abgelaufen', 'Abgelaufen')], default='entwurf', max_length=20, verbose_name='Status')),
                ('betreff', models.CharField(blank=True, max_length=300, verbose_name='Betreff')),
                ('einleitungstext', models.TextField(blank=True, verbose_name='Einleitungstext')),
                ('schlusstext', models.TextField(blank=True, verbose_name='Schlusstext')),
                ('interne_notizen', models.TextField(blank=True, verbose_name='Interne Notizen (erscheint nicht im PDF)')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Angebot',
                'verbose_name_plural': 'Angebote',
                'ordering': ['-datum', '-nummer'],
            },
        ),
        migrations.CreateModel(
            name='Artikel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bezeichnung', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('einheit', models.CharField(default='Std.', help_text='z.B. Std., Stk., pauschal', max_length=50, verbose_name='Einheit')),
                ('einzelpreis', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis (€)')),
                ('steuersatz', models.DecimalField(choices=[(0.0, '0 % (steuerfrei)'), (7.0, '7 % (ermäßigt)'), (19.0, '19 % (Regelsteuersatz)')], decimal_places=2, default=19.0, max_digits=5, verbose_name='Steuersatz')),
                ('aktiv', models.BooleanField(default=True, verbose_name='Aktiv')),
            ],
            options={
                'verbose_name': 'Artikel',
                'verbose_name_plural': 'Artikel',
                'ordering': ['bezeichnung'],
            },
        ),
        migrations.CreateModel(
            name='Einstellungen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma_name', models.CharField(max_length=200, verbose_name='Firmenname')),
                ('firma_zusatz', models.CharField(blank=True, max_length=200, verbose_name='Zusatz')),
                ('strasse', models.CharField(max_length=200, verbose_name='Straße')),
                ('plz', models.CharField(max_length=10, verbose_name='PLZ')),
                ('ort', models.CharField(max_length=100, verbose_name='Ort')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('logo', models.ImageField(blank=True, upload_to='logo/', verbose_name='Logo')),
                ('steuernummer', models.CharField(blank=True, max_length=50, verbose_name='Steuernummer')),
                ('ust_id', models.CharField(blank=True, max_length=50, verbose_name='USt-IdNr.')),
                ('bank_name', models.CharField(blank=True, max_length=100, verbose_name='Bank')),
                ('iban', models.CharField(blank=True, max_length=50, verbose_name='IBAN')),
                ('bic', models.CharField(blank=True, max_length=20, verbose_name='BIC')),
                ('angebot_prefix', models.CharField(default='AN', max_length=10, verbose_name='Angebot-Präfix')),
                ('angebot_naechste_nummer', models.IntegerField(default=1, verbose_name='Nächste Angebotsnummer')),
                ('angebot_format', models.CharField(default='{prefix}-{jahr}-{nummer:04d}', help_text='Platzhalter: {prefix}, {jahr}, {nummer:04d} → z.B. AN-2026-0001', max_length=50, verbose_name='Angebot-Format')),
                ('rechnung_prefix', models.CharField(default='RE', max_length=10, verbose_name='Rechnung-Präfix')),
                ('rechnung_naechste_nummer', models.IntegerField(default=1, verbose_name='Nächste Rechnungsnummer')),
                ('rechnung_format', models.CharField(default='{prefix}-{jahr}-{nummer:04d}', help_text='Platzhalter: {prefix}, {jahr}, {nummer:04d} → z.B. RE-2026-0001', max_length=50, verbose_name='Rechnung-Format')),
                ('angebot_einleitung', models.TextField(blank=True, verbose_name='Angebot Einleitungstext')),
                ('angebot_schlusstext', models.TextField(blank=True, verbose_name='Angebot Schlusstext')),
                ('rechnung_einleitung', models.TextField(blank=True, verbose_name='Rechnung Einleitungstext')),
                ('rechnung_schlusstext', models.TextField(blank=True, verbose_name='Rechnung Schlusstext')),
                ('zahlungsbedingungen', models.TextField(blank=True, default='Zahlbar innerhalb von 14 Tagen ohne Abzug.', verbose_name='Zahlungsbedingungen')),
            ],
            options={
                'verbose_name': 'Einstellungen',
            },
        ),
        migrations.CreateModel(
            name='Kunde',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firma', models.CharField(blank=True, max_length=200, verbose_name='Firma')),
                ('ansprechpartner', models.CharField(blank=True, max_length=200, verbose_name='Ansprechpartner')),
                ('strasse', models.CharField(max_length=200, verbose_name='Straße')),
                ('plz', models.CharField(max_length=10, verbose_name='PLZ')),
                ('ort', models.CharField(max_length=100, verbose_name='Ort')),
                ('land', models.CharField(default='Deutschland', max_length=100, verbose_name='Land')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='E-Mail')),
                ('telefon', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('website', models.URLField(blank=True, verbose_name='Website')),
                ('ust_id', models.CharField(blank=True, max_length=50, verbose_name='USt-IdNr.')),
                ('notizen', models.TextField(blank=True, verbose_name='Notizen')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Kunde',
                'verbose_name_plural': 'Kunden',
                'ordering': ['firma', 'ansprechpartner'],
            },
        ),
        migrations.CreateModel(
            name='Vorlage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
                ('typ', models.CharField(choices=[('angebot', 'Angebot'), ('rechnung', 'Rechnung')], max_length=20, verbose_name='Typ')),
                ('html_inhalt', models.TextField(verbose_name='HTML-Inhalt')),
                ('ist_standard', models.BooleanField(default=False, verbose_name='Standardvorlage')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Vorlage',
                'verbose_name_plural': 'Vorlagen',
            },
        ),
        migrations.CreateModel(
            name='AngebotPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reihenfolge', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('bezeichnung', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('menge', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Menge')),
                ('einheit', models.CharField(default='Std.', max_length=50, verbose_name='Einheit')),
                ('einzelpreis', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis (€)')),
                ('steuersatz', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='Steuersatz (%)')),
                ('angebot', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='core.angebot')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positionen',
                'ordering': ['reihenfolge'],
            },
        ),
        migrations.AddField(
            model_name='angebot',
            name='kunde',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.kunde', verbose_name='Kunde'),
        ),
        migrations.CreateModel(
            name='Rechnung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=50, unique=True, verbose_name='Rechnungsnummer')),
                ('datum', models.DateField(default=django.utils.timezone.now, verbose_name='Rechnungsdatum')),
                ('faellig_am', models.DateField(blank=True, null=True, verbose_name='Fällig am')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('gesendet', 'Gesendet'), ('bezahlt', 'Bezahlt'), ('ueberfaellig', 'Überfällig'), ('storniert', 'Storniert')], default='entwurf', max_length=20, verbose_name='Status')),
                ('betreff', models.CharField(blank=True, max_length=300, verbose_name='Betreff')),
                ('einleitungstext', models.TextField(blank=True, verbose_name='Einleitungstext')),
                ('schlusstext', models.TextField(blank=True, verbose_name='Schlusstext')),
                ('zahlungsbedingungen', models.TextField(blank=True, verbose_name='Zahlungsbedingungen')),
                ('interne_notizen', models.TextField(blank=True, verbose_name='Interne Notizen (erscheint nicht im PDF)')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('angebot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.angebot', verbose_name='Aus Angebot erstellt')),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.kunde', verbose_name='Kunde')),
                ('vorlage', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vorlage', verbose_name='Vorlage')),
            ],
            options={
                'verbose_name': 'Rechnung',
                'verbose_name_plural': 'Rechnungen',
                'ordering': ['-datum', '-nummer'],
            },
        ),
        migrations.CreateModel(
            name='RechnungPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reihenfolge', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('bezeichnung', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('menge', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Menge')),
                ('einheit', models.CharField(default='Std.', max_length=50, verbose_name='Einheit')),
                ('einzelpreis', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis (€)')),
                ('steuersatz', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='Steuersatz (%)')),
                ('rechnung', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='core.rechnung')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positionen',
                'ordering': ['reihenfolge'],
            },
        ),
        migrations.AddField(
            model_name='angebot',
            name='vorlage',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.vorlage', verbose_name='Vorlage'),
        ),
    ]
