# Generated by Django 6.0.2 on 2026-02-26 19:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angebot',
            name='nummer',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Angebotsnummer'),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='nummer',
            field=models.CharField(blank=True, max_length=50, unique=True, verbose_name='Rechnungsnummer'),
        ),
    ]
