# Generated by Django 6.0.2 on 2026-02-27 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_angebot_nummer_alter_rechnung_nummer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='angebot',
            name='nummer',
            field=models.CharField(max_length=50, unique=True, verbose_name='Angebotsnummer'),
        ),
        migrations.AlterField(
            model_name='angebotposition',
            name='einzelpreis',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis inkl. MwSt. (€)'),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='nummer',
            field=models.CharField(max_length=50, unique=True, verbose_name='Rechnungsnummer'),
        ),
        migrations.AlterField(
            model_name='rechnungposition',
            name='einzelpreis',
            field=models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis inkl. MwSt. (€)'),
        ),
    ]
