# Generated by Django 6.0.2 on 2026-03-04 10:41

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_angebot_nummer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='einstellungen',
            name='gutschrift_format',
            field=models.CharField(default='{prefix}-{jahr}-{nummer:04d}', max_length=50, verbose_name='Gutschrift-Format'),
        ),
        migrations.AddField(
            model_name='einstellungen',
            name='gutschrift_naechste_nummer',
            field=models.IntegerField(default=1, verbose_name='Nächste Gutschriftnummer'),
        ),
        migrations.AddField(
            model_name='einstellungen',
            name='gutschrift_prefix',
            field=models.CharField(default='GS', max_length=10, verbose_name='Gutschrift-Präfix'),
        ),
        migrations.AlterField(
            model_name='rechnung',
            name='status',
            field=models.CharField(choices=[('entwurf', 'Entwurf'), ('gesendet', 'Gesendet'), ('bezahlt', 'Bezahlt'), ('ueberfaellig', 'Überfällig'), ('storniert', 'Storniert'), ('teilgutgeschrieben', 'Teilgutgeschrieben')], default='entwurf', max_length=20, verbose_name='Status'),
        ),
        migrations.CreateModel(
            name='Gutschrift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nummer', models.CharField(max_length=50, unique=True, verbose_name='Gutschriftnummer')),
                ('datum', models.DateField(default=django.utils.timezone.now, verbose_name='Datum')),
                ('status', models.CharField(choices=[('entwurf', 'Entwurf'), ('gesendet', 'Gesendet'), ('storniert', 'Storniert')], default='entwurf', max_length=20, verbose_name='Status')),
                ('betreff', models.CharField(blank=True, max_length=300, verbose_name='Betreff')),
                ('einleitungstext', models.TextField(blank=True, verbose_name='Einleitungstext')),
                ('schlusstext', models.TextField(blank=True, verbose_name='Schlusstext')),
                ('interne_notizen', models.TextField(blank=True, verbose_name='Interne Notizen')),
                ('erstellt_am', models.DateTimeField(auto_now_add=True)),
                ('geaendert_am', models.DateTimeField(auto_now=True)),
                ('kunde', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.kunde', verbose_name='Kunde')),
                ('rechnung', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gutschriften', to='core.rechnung', verbose_name='Zu Rechnung')),
            ],
            options={
                'verbose_name': 'Gutschrift',
                'verbose_name_plural': 'Gutschriften',
                'ordering': ['-datum', '-nummer'],
            },
        ),
        migrations.CreateModel(
            name='GutschriftPosition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reihenfolge', models.PositiveIntegerField(default=0, verbose_name='Reihenfolge')),
                ('bezeichnung', models.CharField(max_length=200, verbose_name='Bezeichnung')),
                ('beschreibung', models.TextField(blank=True, verbose_name='Beschreibung')),
                ('menge', models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Menge')),
                ('einheit', models.CharField(default='Std.', max_length=50, verbose_name='Einheit')),
                ('einzelpreis', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Einzelpreis (€)')),
                ('steuersatz', models.DecimalField(decimal_places=2, default=19.0, max_digits=5, verbose_name='Steuersatz (%)')),
                ('gutschrift', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='positionen', to='core.gutschrift')),
            ],
            options={
                'verbose_name': 'Position',
                'verbose_name_plural': 'Positionen',
                'ordering': ['reihenfolge'],
            },
        ),
    ]
