# Generated by Django 6.0.2 on 2026-03-06 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_einstellungen_gutschrift_format_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='einstellungen',
            name='hintergrund_pdf',
            field=models.FileField(blank=True, null=True, upload_to='hintergrund/', verbose_name='Hintergrund-PDF'),
        ),
    ]
