# Generated by Django 6.0.2 on 2026-03-06 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_einstellungen_hintergrund_pdf'),
    ]

    operations = [
        migrations.AddField(
            model_name='einstellungen',
            name='firma_zusatz2',
            field=models.CharField(blank=True, max_length=200, verbose_name='Zusatz 2'),
        ),
    ]
