# Generated by Django 6.0.2 on 2026-03-09 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_einstellungen_firma_zusatz2'),
    ]

    operations = [
        migrations.AddField(
            model_name='einstellungen',
            name='email_angebot_anhang1',
            field=models.FileField(blank=True, null=True, upload_to='email_anhaenge/', verbose_name='Standard-Anhang 1 (Angebot)'),
        ),
        migrations.AddField(
            model_name='einstellungen',
            name='email_angebot_anhang2',
            field=models.FileField(blank=True, null=True, upload_to='email_anhaenge/', verbose_name='Standard-Anhang 2 (Angebot)'),
        ),
        migrations.AddField(
            model_name='einstellungen',
            name='email_angebot_betreff',
            field=models.CharField(blank=True, default='Angebot {{nummer}} – {{firma}}', help_text='Platzhalter: {{nummer}}, {{kundenname}}, {{firma}}, {{datum}}', max_length=200, verbose_name='Betreff-Vorlage Angebot'),
        ),
        migrations.AddField(
            model_name='einstellungen',
            name='email_angebot_text',
            field=models.TextField(blank=True, verbose_name='E-Mail-Text Angebot'),
        ),
    ]
