# Generated by Django 6.0.2 on 2026-03-10 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_einstellungen_email_angebot_anhang1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='einstellungen',
            name='email_gutschrift_anhang1',
            field=models.FileField(blank=True, null=True, upload_to='email_anhaenge/', verbose_name='Standard-Anhang 1 (Gutschrift)'),
        ),
        migrations.AddField(
            model_name='einstellungen',
            name='email_gutschrift_anhang2',
            field=models.FileField(blank=True, null=True, upload_to='email_anhaenge/', verbose_name='Standard-Anhang 2 (Gutschrift)'),
        ),
        migrations.AddField(
            model_name='einstellungen',
            name='email_gutschrift_betreff',
            field=models.CharField(blank=True, default='Gutschrift {{nummer}} – {{firma}}', help_text='Platzhalter: {{nummer}}, {{kundenname}}, {{firma}}, {{datum}}', max_length=200, verbose_name='Betreff-Vorlage Gutschrift'),
        ),
        migrations.AddField(
            model_name='einstellungen',
            name='email_gutschrift_text',
            field=models.TextField(blank=True, verbose_name='E-Mail-Text Gutschrift'),
        ),
        migrations.AddField(
            model_name='einstellungen',
            name='email_rechnung_anhang1',
            field=models.FileField(blank=True, null=True, upload_to='email_anhaenge/', verbose_name='Standard-Anhang 1 (Rechnung)'),
        ),
        migrations.AddField(
            model_name='einstellungen',
            name='email_rechnung_anhang2',
            field=models.FileField(blank=True, null=True, upload_to='email_anhaenge/', verbose_name='Standard-Anhang 2 (Rechnung)'),
        ),
        migrations.AddField(
            model_name='einstellungen',
            name='email_rechnung_betreff',
            field=models.CharField(blank=True, default='Rechnung {{nummer}} – {{firma}}', help_text='Platzhalter: {{nummer}}, {{kundenname}}, {{firma}}, {{datum}}', max_length=200, verbose_name='Betreff-Vorlage Rechnung'),
        ),
        migrations.AddField(
            model_name='einstellungen',
            name='email_rechnung_text',
            field=models.TextField(blank=True, verbose_name='E-Mail-Text Rechnung'),
        ),
    ]
