# Generated by Django 6.0.2 on 2026-03-11 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_rechnung_zahlungseingang'),
    ]

    operations = [
        migrations.AddField(
            model_name='angebot',
            name='gesendet_am',
            field=models.DateField(blank=True, null=True, verbose_name='Gesendet am'),
        ),
        migrations.AddField(
            model_name='rechnung',
            name='gesendet_am',
            field=models.DateField(blank=True, null=True, verbose_name='Gesendet am'),
        ),
    ]
